-- migrate:up


CREATE TABLE IF NOT EXISTS posts (
    id SERIAL PRIMARY KEY,
    en BOOLEAN DEFAULT TRUE,
    owner_id INTEGER NOT NULL,
    name VARCHAR(250) NOT NULL,
    content VARCHAR(1500) NOT NULL DEFAULT '',
    likes INTEGER NOT NULL DEFAULT 0,
    dislikes INTEGER NOT NULL DEFAULT 0,
    ctime TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() at time zone 'utc'),
    atime TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL,
    dtime TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL
);


-- migrate:down


DROP TABLE posts CASCADE;
